General:
  WordName: "orerun"
  MinPlayers: 2
  ChatFormat: "{DisplayName}: {Message}"
  FriendlyFire: false
  teams:
    red:
      name: "Red"
      color: "&c"
      item: "minecraft:banner/1"
      MaxPlayers: 2
      spawns: -3.6, 68, 42.5, 88.5f, 1.3f
    blue:
      name: "Blue"
      color: "&9"
      item: "minecraft:banner/12"
      MaxPlayers: 2
      spawns: -71.441, 89, 50.6, -165.4f, 3.7f
    yellow:
      name: "Yellow"
      color: "&e"
      item: "minecraft:banner/11"
      MaxPlayers: 2
      spawns: -56.540, 76, 143.5, 176.6f, 3.4f

Locations:
  Lobby: 0, 104, 1, -93f, 2.6f
  GameCenter: 0, 0, 0, 0f, 0f
  DepositChest: 0.442, 85, 3.470, -30.7f, -17.5f

Timers:
  StartTime: 120
  GameTime: 2400
  ChestTime: 1200
  #Time (Based: GameTime), Remove Block, SmoothDelay
  Steps:
    - "600, 65, 5"
    - "1200, 50, 5"
    - "1800, 60, 5"
    - "2100, 45, 10"
    - "2250, 40, 15"

WorldBorder:
  LobbySize: 300
  GameSize: 300
  DamageAmount: 0.5
  DamageBuffer: 1
  WarningBlock: 15
  
Points:
  Items:
    - "COAL:30"
    - "IRON_INGOT:150"
    - "GOLD_INGOT:200"
    - "DIAMOND:400"
    - "EMERALD:550"
